version: '3.5'

services:
  graphql_query_operators:
    container_name: graphql_query_operators
    build: .
    stdin_open: true
    tty: true
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/graphql_query_operators
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    ports:
      - 127.0.0.1:27019:27017
    volumes:
      - ./data:/data
